// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package apperrors

import (
	"errors"
	"fmt"
)

const (
	// AlertFailedSubscription is a Alert of type failed-subscription.
	// Used for events where a user attempts to subscribe but fails after payment (stripe) and may require developer intervention.
	AlertFailedSubscription Alert = "failed-subscription"
)

var ErrInvalidAlert = errors.New("not a valid Alert")

// String implements the Stringer interface.
func (x Alert) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Alert) IsValid() bool {
	_, err := ParseAlert(string(x))
	return err == nil
}

var _AlertValue = map[string]Alert{
	"failed-subscription": AlertFailedSubscription,
}

// ParseAlert attempts to convert a string to a Alert.
func ParseAlert(name string) (Alert, error) {
	if x, ok := _AlertValue[name]; ok {
		return x, nil
	}
	return Alert(""), fmt.Errorf("%s is %w", name, ErrInvalidAlert)
}
