// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FeedMessage struct {
	ID             uuid.UUID
	FeedSlug       string
	RawRequest     []byte
	RawHeaders     []byte
	Title          *string
	Message        *string
	Priority       *int32
	Logs           []string
	Metadata       []byte
	State          *string
	StateChangedAt pgtype.Timestamp
	ReceivedAt     time.Time
	ProcessedAt    pgtype.Timestamp
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SearchVector   interface{}
}

type FeedMessagesView struct {
	ID             uuid.UUID
	FeedSlug       string
	RawRequest     []byte
	RawHeaders     []byte
	Title          *string
	Message        *string
	Priority       *int32
	Logs           []string
	Metadata       []byte
	State          *string
	StateChangedAt pgtype.Timestamp
	ReceivedAt     time.Time
	ProcessedAt    pgtype.Timestamp
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID                    uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Username              string
	Email                 string
	PasswordHash          string
	IsAdmin               bool
	StripeCustomerID      *string
	StripeSubscriptionID  *string
	SubscriptionStartDate pgtype.Timestamp
	SubscriptionEndedDate pgtype.Timestamp
}

type UserActionToken struct {
	ID        uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	UserID    uuid.UUID
	Token     []byte
	Action    string
}

type UserSession struct {
	ID        uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	UserID    uuid.UUID
	Token     []byte
}
