name: Go Build/Test

on:
  workflow_call:

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'backend/go.mod'

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v8
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          args: --timeout=6m
          working-directory: backend

      - name: Test
        run: go test ./... -race
        working-directory: backend
